---
version: '3.7'
services:

  prometheus:
    image: prom/prometheus:v2.37.7  
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    ports:
    - 9090:9090
    expose:
    - 9090
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 256M

  grafana:
    image: grafana/grafana:11.1.0
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/public/img/icons/confluent:/usr/share/grafana/public/img/icons/confluent
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    restart: unless-stopped
    ports:
    - 3000:3000
    expose:
      - 3000
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 256M

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    restart: always
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    ports:
    - 9093:9093
    expose:
      - 9093
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 256M
    

  confluent_cost_exporter:
    image: docker.io/mcolomerc/confluent-costs-exporter:latest
    platform: linux/amd64
    container_name: confluent_cost_exporter
   # command:
    #  - '--storage.tsdb.retention.time=100d'
    environment:
    - CONFLUENT_CLOUD_API_KEY=S5EVU4GA7NFULYQL
    - CONFLUENT_CLOUD_API_SECRET=kDaccqwkz8ikzaDqZOV1S9Z8m1vWW0nH8xQyXt21ODgk/sBKQr6EEEejSly2JqsF
    - CACHE_EXPIRATION=240m
    - PORT=7979
    ports:
      - 7979:7979


volumes:
    prometheus_data: {}
    grafana_data: {}
   # alertmanager_data: {}
