global:
 scrape_interval: 10s
 evaluation_interval: 10s

rule_files:
 - /etc/prometheus/rules.yml

alerting:
 alertmanagers:
   - static_configs:
       - targets:
           - alertmanager:9093

scrape_configs:
  - job_name: Confluent Cloud
    scrape_interval: 1m
    scrape_timeout: 1m
    honor_timestamps: true
    static_configs:
      - targets:
        - api.telemetry.confluent.cloud
    scheme: https
    basic_auth:
      username: <<ccloud_api_key>>
      password: <<cloud_api_secret>>
    metrics_path: /v2/metrics/cloud/export
    params:
      #kafka cluster id - add multiple if required
      "resource.kafka.id": 
        - lkc-xxxxxx
      #connector id - add multiple if required
      "resource.connector.id": 
        - lcc-xxxxxx
      #ksql id - add multiple if required
      "resource.ksql.id": 
        - lksqlc-xxxxxx
      #schema registry id - add multiple if required
      "resource.schema_registry.id": 
        - lsrc-xxxxxx

  - job_name: Confluent Cost Exporter
    scrape_interval: 5m
    scrape_timeout: 30s
    honor_labels: true
    metrics_path: /probe
    static_configs:
      - targets: ['confluent_cost_exporter:7979']
