groups:
  - name: kafka-alerts
    rules:
      - alert: KafkaHighConnectionCount
        expr: max(avg_over_time(confluent_kafka_server_active_connection_count[10m])) > 50
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High Kafka Connection Count"
          description: "Total active connections across Kafka servers have exceeded 50. Current total: {{ $value }}."
