groups:
  - name: kafka-alerts
    rules:
      - alert: HighKafkaConnectionCount
        expr: sum(confluent_kafka_server_active_connection_count{kafka_id="lkc-7d9gwj",}) > 40
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "High number of active Kafka connections"
          description: "Active Kafka connections are greater than 40 (current value: {{ $value }})"
